#! /bin/sh

# with serial its easier to read the logs

echo "MULLE_HOSTNAME=\"${MULLE_HOSTNAME}\"" 2>&1

mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" extension show &&
mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d exe -m mulle-web/webclient-developer executable &&
cd exe &&
(
   echo "Adding environment-host-travis-ci-prerelease file from MulleWebClient/test" >&2 &&
   cd .mulle/etc/env &&
   curl -L -O "https://raw.githubusercontent.com/MulleWeb/MulleWebClient/prerelease/test/.mulle/etc/env/environment-host-travis-ci-prerelease.sh" >&2
) &&
mulle-sde hostname &&
mulle-sde environment --global set MULLE_CRAFT_USE_SCRIPT YES &&
mulle-sde environment &&
mulle-sde craft --release &&
cd .. &&
mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d exe2 -m mulle-web/webserver-developer executable &&
cd exe2 &&
(
   echo "Adding environment-host-travis-ci-prerelease file from MulleWebServer/test" >&2 &&
   cd .mulle/etc/env &&
   curl -L -O "https://raw.githubusercontent.com/MulleWeb/MulleWebServer/prerelease/test/.mulle/etc/env/environment-host-travis-ci-prerelease.sh" >&2
) &&
mulle-sde environment --global set MULLE_CRAFT_USE_SCRIPT YES &&
mulle-sde craft
